# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "mix" # See documentation for possible values
    directory: "/apps/collector" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "mix" # See documentation for possible values
    directory: "/apps/dashboard" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "mix" # See documentation for possible values
    directory: "/apps/data" # Location of package manifests
    schedule:
      interval: "daily"
