[package]
name = "exlytics"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43", features = ["full"] }
httparse = { version = "1.9" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
