version: "3.7"
services:
  timescaledb:
    image: timescale/timescaledb:1.6.1-pg11
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  exlytics:
    build:
      context: .
    depends_on:
      - timescaledb
    ports:
      - 8081:80
