version: "3.8"
services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes: 
      - ./priv/create.sql:/docker-entrypoint-initdb.d/create.sql
