resources:
  - ../base

namePrefix: integration-

commonLabels:
  application: integration-exlytics

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: exlytics
    spec:
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: application
                        operator: In
                        values:
                          - integration-exlytics
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: nginx
              envFrom:
                - secretRef:
                    name: exlytics-integration-b72hkm782k
