resources:
  - ../base

namePrefix: integration-

commonLabels:
  application: integration-exlytics

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: exlytics
    spec:
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: distribute
                        operator: In
                        values:
                          - always
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: nginx
              envFrom:
                - secretRef:
                    name: exlytics-integration-b72hkm782k
  - |-
    apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: exlytics
    spec:
      jobTemplate:
        spec:
          template:
            spec:
              containers:
                - name: nginx
                  envFrom:
                    - secretRef:
                        name: exlytics-integration-b72hkm782k
