resources:
  - ../base

namePrefix: integration-

commonLabels:
  application: integration-exlytics

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: exlytics
    spec:
      template:
        spec:
          containers:
            - name: nginx
              envFrom:
                - secretRef:
                    name: exlytics-integration-b72hkm782k
