apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: exlytics
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: nginx
              image: nginx:latest
              args:
                - mix
                - run
                - -e
                - "Exlytics.Aggregation.rebuild()"
          restartPolicy: OnFailure
