apiVersion: apps/v1
kind: Deployment
metadata:
  name: exlytics
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          envFrom:
            - secretRef:
                name: exlytics
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 80
          resources:
            requests:
              cpu: 25m
              memory: "75Mi"
