name: branch-protection
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4
        with:
          components: clippy
      - run: cargo clippy --no-deps -- -D warnings
  test:
    runs-on: ubuntu-latest
    env:
      TEST_DATABASE_URL: "postgres://exlytics@localhost:5432/exlytics"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - run: docker run -d -p 5432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGRES_USER=exlytics -e POSTGRES_DB=exlytics -v ./migrations/schema.sql:/docker-entrypoint-initdb.d/schema.sql postgres:17.4
      - uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4
      - run: cargo test
