name: Continuous deployment

on:
  push:
    branches:
      - integration

jobs:
  ci:
    name: Continuous deployment
    runs-on: self-hosted

    steps:
      - name: Start job
        run: kubectl create job
