name: Production
on:
  push:
    branches:
      - main

env:
  CLOUDSDK_COMPUTE_REGION: us-central1
  CLOUDSDK_COMPUTE_ZONE: us-central1-c

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Elixir
        uses: actions/setup-elixir@master
        with:
          otp-version: 22.3.2
          elixir-version: 1.10.3

      - name: Install GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "292.0.0"
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud --quiet auth configure-docker

      - name: Download dependencies
        run: mix deps.get

      - name: Build release
        run: MIX_ENV=prod mix release

      - name: Create image
        run: docker build --build-arg release=_build/prod/rel/exlytics -t ${{ secrets.IMAGE_TAG }}:${{ github.sha }} .

      - name: Push image
        run: docker push ${{ secrets.IMAGE_TAG }}:${{ github.sha }}

      - name: Configure kubectl
        run: gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }}

      - name: Deploy
        run: kubectl --namespace production set image --record deployment/exlytics exlytics=${{ secrets.IMAGE_TAG }}:${{ github.sha }}
